# -*- coding: utf-8 -*-
"""1-Linear Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYKREnJsahbUbG3D1eo3k4CEQ60tdBsQ
"""

import time
import random
import matplotlib.pyplot as plt

def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1


sizes = [1500, 5500, 10500, 60000, 400000, 500000]
times = []

def measure_time(n):
    arr = random.sample(range(n * 2), n)
    target = random.choice(arr)

    start_time = time.time()
    linear_search(arr, target)
    end_time = time.time()

    return end_time - start_time

for n in sizes:
    t = measure_time(n)
    times.append(t)
    print(f"n = {n}, Time Taken = {t:.6f} seconds")
plt.plot(sizes, times, marker='o', linestyle='-', color='b', label='Linear Search Time')
plt.xlabel('Number of Elements (n)')
plt.ylabel('Time Taken (seconds)')
plt.title('Linear Search Time Complexity')
plt.legend()
plt.grid()
plt.show()